name: notifikasi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_local_notifications: 14.0.1
  http: 0.13.6
  shared_preferences: 2.1.1
  intl: 0.18.1
  convex_bottom_bar: 3.2.0
  loading_animation_widget: 1.2.0+4
  timezone: 0.9.2
  flutter_native_timezone: 2.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

